name: weather_data_usa
services:
  db:
    container_name: database
    image: postgres:16
    environment:
      POSTGRES_USER: weather # just for testing
      POSTGRES_PASSWORD: weatherpass # just for testing
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - weather_network

  backend:
    container_name: weather_backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://weather:weatherpass@database/weatherdb # just for testing
    depends_on:
      - db
    restart: always
    networks:
      - weather_network

  frontend:
    container_name: weather_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - weather_network

  nginx:
    container_name: weather_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - weather_network

volumes:
  pgdata:

networks:
  weather_network:
    driver: bridge