openapi: 3.0.0
info:
  title: Weather API
  version: 1.0.0
  description: API for weather stations and observations
servers:
  - url: /api
paths:
  /stations:
    get:
      summary: Get all weather stations
      responses:
        '200':
          description: A list of weather stations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Station'
  /observations/latest:
    get:
      summary: Get latest observation for a station
      parameters:
        - in: query
          name: station_id
          schema:
            type: string
          required: true
          description: Station identifier
      responses:
        '200':
          description: Latest observation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Observation'
  /observations:
    post:
      summary: Store a weather observation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObservationInput'
      responses:
        '200':
          description: Observation stored
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Observation'
  /observations/range:
    get:
      summary: Get observations for a station in a time range
      parameters:
        - in: query
          name: station_id
          schema:
            type: string
          required: true
          description: Station identifier
        - in: query
          name: start
          schema:
            type: string
            format: date-time
          required: true
          description: Start of time range (ISO 8601)
        - in: query
          name: end
          schema:
            type: string
            format: date-time
          required: true
          description: End of time range (ISO 8601)
      responses:
        '200':
          description: Observations in range
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Observation'
  /variables:
    get:
      summary: Get all available observation variables
      responses:
        '200':
          description: List of variable names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  schemas:
    Station:
      type: object
      properties:
        station_identifier:
          type: string
        longitude:
          type: number
        latitude:
          type: number
    StationInput:
      type: object
      required:
        - station_identifier
        - longitude
        - latitude
      properties:
        station_identifier:
          type: string
        longitude:
          type: number
        latitude:
          type: number
    Observation:
      type: object
      properties:
        station:
          type: string
        parameter_name:
          type: string
        parameter_unit:
          type: string
        value:
          type: number
        observed_at:
          type: string
    ObservationInput:
      type: object
      required:
        - station_id
        - parameter_name
        - parameter_unit
        - value
        - observed_at
      properties:
        station_id:
          type: string
        parameter_name:
          type: string
        parameter_unit:
          type: string
        value:
          type: number
        observed_at:
          type: string